### PR TITLE
Add in CHANGELOG.md

### LINKED ISSUE #4: Add in a CHANGELOG
We should add a `CHANGELOG` to track changes between releases.

### PR DESCRIPTION
**Pull request by brettlangdon**
We have released version `0.1.0` so we should begin to maintain a changelog of releases.

This PR adds in the `CHANGELOG.md`

Fixes #4 

/cc @twolfson

### CODE REVIEW

**Comment by twolfson** [comment]
Ewww, `0.1.0`. `1.0.0` ftw (avoiding those semver "minor can be breaking change" issues)

**Comment by twolfson** [comment]
Looks good :+1:

**Comment by brettlangdon** [comment]
Yeah, I always default my projects to `0.1.0`, was on auto-pilot here for this one.

**Comment by twolfson** [comment]
Got to adjust your autopilot -- my boilerplates now always have `1.0.0` in their CHANGELOGs and a default version of `1.0.0` ;)

**Pull request merged**
